name: linux-x64-build-android-ndk-r23b (libamice.so via clang-r416183c1)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      AMICE_DIR: ${{ github.workspace }}/amice
      OUT_DIR: ${{ github.workspace }}/out
      CLANG_DIR: ${{ github.workspace }}/clang-r416183c1
      CLANG_UNSTRIPPED_URL: "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/c3260b409f13d92f8c9f4795420238694c529352/clang-r416183c1.tar.gz"

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4

      - name: Checkout amice source
        uses: actions/checkout@v4
        with:
          repository: fuqiuluo/amice
          ref: master
          path: amice

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo (amice)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ env.AMICE_DIR }}/target-llvm12
          key: ${{ runner.os }}-cargo-amice-${{ hashFiles('amice/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-amice-

      - name: Prepare folders
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$OUT_DIR" "$CLANG_DIR"

      - name: Download unstripped Clang r416183c1 (LLVM 12)
        shell: bash
        run: |
          set -euo pipefail
          curl -fL "$CLANG_UNSTRIPPED_URL" -o /tmp/clang-r416183c1.tar.gz
          tar -xzf /tmp/clang-r416183c1.tar.gz -C "$CLANG_DIR"
          "$CLANG_DIR/bin/clang++" --version || true
          ls -l "$CLANG_DIR/lib"  || true
          ls -l "$CLANG_DIR/lib64" || true

      - name: Normalize LLVM dylib name (handle libLLVM-12git.so)
        shell: bash
        run: |
          set -euo pipefail
          FOUND="$(find "$CLANG_DIR" -maxdepth 3 -type f -name 'libLLVM-12*.so' | head -n1 || true)"
          if [ -z "$FOUND" ]; then
            echo "libLLVM-12*.so not found under $CLANG_DIR"
            find "$CLANG_DIR" -maxdepth 3 -name 'libLLVM*.so' -ls || true
            exit 1
          fi
          LIBDIR="$(dirname "$FOUND")"
          BASENAME="$(basename "$FOUND")"
          ln -sf "$BASENAME" "$LIBDIR/libLLVM-12.so"
          ln -sf "$BASENAME" "$LIBDIR/libLLVM.so"
          ls -l "$LIBDIR"/libLLVM*.so

          {
            echo "LLVM_SYS_120_PREFIX=$CLANG_DIR"
            echo "LD_LIBRARY_PATH=$LIBDIR"
            echo "LIBRARY_PATH=$LIBDIR"
            echo "PATH=$CLANG_DIR/bin:${PATH}"
            echo "CC=$CLANG_DIR/bin/clang"
            echo "CXX=$CLANG_DIR/bin/clang++"
            echo "CARGO_TARGET_DIR=${{ env.AMICE_DIR }}/target-llvm12"
          } >> "$GITHUB_ENV"

          {
            echo "RUSTFLAGS=-C linker=$CLANG_DIR/bin/clang -C link-arg=-fuse-ld=lld"
            echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=$CLANG_DIR/bin/clang"
          } >> "$GITHUB_ENV"

          if [ -x "$CLANG_DIR/bin/llvm-config" ]; then
            echo "LLVM_CONFIG_PATH=$CLANG_DIR/bin/llvm-config" >> "$GITHUB_ENV"
          fi

      - name: Reset ffi.cc & ensure <cstddef> is included
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          git checkout -- amice-llvm/cpp/ffi.cc || true
          f="amice-llvm/cpp/ffi.cc"
          if ! grep -q '<cstddef>' "$f"; then
            sed -i '1i #include <cstddef>' "$f"
          fi

      - name: Patch build.rs to compile extra shim TU (cpp/llvm12_cfgshim.cc)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          br="amice-llvm/build.rs"
          if ! grep -q 'llvm12_cfgshim.cc' "$br"; then
            awk '
              /[.]file\("cpp\/ffi[.]cc"\)/ && !done {
                print $0
                print "        .file(\"cpp/llvm12_cfgshim.cc\")"
                done=1
                next
              }
              { print $0 }
            ' "$br" > "${br}.tmp"
            mv "${br}.tmp" "$br"
          fi
          grep -n 'llvm12_cfgshim.cc' "$br" || true

      - name: Create cpp/llvm12_cfgshim.cc (No-Op CFG simplify + LLVMIsTypeAttribute stub)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          mkdir -p amice-llvm/cpp
          SHIM_FILE="amice-llvm/cpp/llvm12_cfgshim.cc"
          echo '// This translation unit provides missing createCFGSimplificationPass symbols for LLVM 12-based NDKs' > "$SHIM_FILE"
          echo '#include <functional>' >> "$SHIM_FILE"
          echo '#include "llvm/IR/Function.h"' >> "$SHIM_FILE"
          echo '#include "llvm/Pass.h"' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo 'namespace llvm { struct SimplifyCFGOptions; }' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo '#if defined(LLVM_VERSION_MAJOR) && (LLVM_VERSION_MAJOR < 13)' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo 'namespace {' >> "$SHIM_FILE"
          echo '  struct NoOpCFGSimplifyPass : public ::llvm::FunctionPass {' >> "$SHIM_FILE"
          echo '    static char ID;' >> "$SHIM_FILE"
          echo '    NoOpCFGSimplifyPass() : ::llvm::FunctionPass(ID) {}' >> "$SHIM_FILE"
          echo '    bool runOnFunction(::llvm::Function&) override { return false; }' >> "$SHIM_FILE"
          echo '  };' >> "$SHIM_FILE"
          echo '  char NoOpCFGSimplifyPass::ID = 0;' >> "$SHIM_FILE"
          echo '}' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo '// 1) zero-arg variant' >> "$SHIM_FILE"
          echo 'extern "C" ::llvm::FunctionPass* amice_cfgsimplify_zero()' >> "$SHIM_FILE"
          echo '  asm("_ZN4llvm27createCFGSimplificationPassEv");' >> "$SHIM_FILE"
          echo '::llvm::FunctionPass* amice_cfgsimplify_zero() {' >> "$SHIM_FILE"
          echo '  return new NoOpCFGSimplifyPass();' >> "$SHIM_FILE"
          echo '}' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo '// 2) (SimplifyCFGOptions, Predicate) variant in newer LLVM' >> "$SHIM_FILE"
          echo 'extern "C" ::llvm::FunctionPass* amice_cfgsimplify_new(' >> "$SHIM_FILE"
          echo '  ::llvm::SimplifyCFGOptions,' >> "$SHIM_FILE"
          echo '  std::function<bool(::llvm::Function const&)>)' >> "$SHIM_FILE"
          echo '  asm("_ZN4llvm27createCFGSimplificationPassENS_18SimplifyCFGOptionsESt8functionIFbRKNS_8FunctionEEE");' >> "$SHIM_FILE"
          echo '::llvm::FunctionPass* amice_cfgsimplify_new(' >> "$SHIM_FILE"
          echo '  ::llvm::SimplifyCFGOptions,' >> "$SHIM_FILE"
          echo '  std::function<bool(::llvm::Function const&)>)' >> "$SHIM_FILE"
          echo '{' >> "$SHIM_FILE"
          echo '  return new NoOpCFGSimplifyPass();' >> "$SHIM_FILE"
          echo '}' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo '// 3) legacy 6-params variant used around LLVM 11/12 in some headers' >> "$SHIM_FILE"
          echo 'extern "C" ::llvm::FunctionPass* amice_cfgsimplify_legacy(' >> "$SHIM_FILE"
          echo '  unsigned, bool, bool, bool, bool,' >> "$SHIM_FILE"
          echo '  std::function<bool(::llvm::Function const&)>)' >> "$SHIM_FILE"
          echo '  asm("_ZN4llvm27createCFGSimplificationPassEjbbbbSt8functionIFbRKNS_8FunctionEEE");' >> "$SHIM_FILE"
          echo '::llvm::FunctionPass* amice_cfgsimplify_legacy(' >> "$SHIM_FILE"
          echo '  unsigned, bool, bool, bool, bool,' >> "$SHIM_FILE"
          echo '  std::function<bool(::llvm::Function const&)>)' >> "$SHIM_FILE"
          echo '{' >> "$SHIM_FILE"
          echo '  return new NoOpCFGSimplifyPass();' >> "$SHIM_FILE"
          echo '}' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo '// Stub missing C-API for LLVM<13' >> "$SHIM_FILE"
          echo 'extern "C" {' >> "$SHIM_FILE"
          echo '  typedef struct LLVMOpaqueAttributeRef *LLVMAttributeRef;' >> "$SHIM_FILE"
          echo '  typedef int LLVMBool;' >> "$SHIM_FILE"
          echo '  LLVMBool LLVMIsTypeAttribute(LLVMAttributeRef) { return 0; }' >> "$SHIM_FILE"
          echo '}' >> "$SHIM_FILE"
          echo '' >> "$SHIM_FILE"
          echo '#endif /* LLVM_VERSION_MAJOR < 13 */' >> "$SHIM_FILE"

      - name: Build libamice.so (feature llvm12-0)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        env:
          CXXFLAGS: -fno-rtti -fno-exceptions -std=c++17 -DLLVM_VERSION_MAJOR=12
        run: |
          set -euo pipefail
          cargo clean
          cargo build --release --no-default-features --features llvm12-0
          mkdir -p "$OUT_DIR"
          cp -v target-llvm12/release/libamice.so "$OUT_DIR/"

      - name: Smoke test:load plugin with this clang
        shell: bash
        run: |
          set -euo pipefail
          echo 'int main(){return 0;}' > /tmp/t.c
          "$CLANG_DIR/bin/clang" -fpass-plugin="$OUT_DIR/libamice.so" -O2 -xc /tmp/t.c -o /tmp/t

      - name: Upload artifact (libamice.so for clang-r416183c1)
        uses: actions/upload-artifact@v4
        with:
          name: libamice-ndk-r23b-clang-r416183c1
          path: ${{ env.OUT_DIR }}/libamice.so
          if-no-files-found: error

