name: linux-x64-build-android-ndk-r23b (libamice.so via clang-r416183c1)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      AMICE_DIR: ${{ github.workspace }}/amice
      OUT_DIR: ${{ github.workspace }}/out
      CLANG_DIR: ${{ github.workspace }}/clang-r416183c1
      CLANG_UNSTRIPPED_URL: "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/c3260b409f13d92f8c9f4795420238694c529352/clang-r416183c1.tar.gz"

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4

      - name: Checkout amice source
        uses: actions/checkout@v4
        with:
          repository: fuqiuluo/amice
          ref: master
          path: amice

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo (amice)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ env.AMICE_DIR }}/target-llvm12
          key: ${{ runner.os }}-cargo-amice-${{ hashFiles('amice/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-amice-

      - name: Prepare folders
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$OUT_DIR" "$CLANG_DIR"

      - name: Download unstripped Clang r416183c1 (LLVM 12)
        shell: bash
        run: |
          set -euo pipefail
          curl -fL "$CLANG_UNSTRIPPED_URL" -o /tmp/clang-r416183c1.tar.gz
          tar -xzf /tmp/clang-r416183c1.tar.gz -C "$CLANG_DIR"
          "$CLANG_DIR/bin/clang++" --version || true
          ls -l "$CLANG_DIR/lib"  || true
          ls -l "$CLANG_DIR/lib64" || true

      - name: Normalize LLVM dylib name (handle libLLVM-12git.so)
        shell: bash
        run: |
          set -euo pipefail
          FOUND="$(find "$CLANG_DIR" -maxdepth 3 -type f -name 'libLLVM-12*.so' | head -n1 || true)"
          if [ -z "$FOUND" ]; then
            echo "libLLVM-12*.so not found under $CLANG_DIR"
            find "$CLANG_DIR" -maxdepth 3 -name 'libLLVM*.so' -ls || true
            exit 1
          fi
          LIBDIR="$(dirname "$FOUND")"
          BASENAME="$(basename "$FOUND")"
          ln -sf "$BASENAME" "$LIBDIR/libLLVM-12.so"
          ln -sf "$BASENAME" "$LIBDIR/libLLVM.so"
          ls -l "$LIBDIR"/libLLVM*.so

          {
            echo "LLVM_SYS_120_PREFIX=$CLANG_DIR"
            echo "LD_LIBRARY_PATH=$LIBDIR:${LD_LIBRARY_PATH:-}"
            echo "LIBRARY_PATH=$LIBDIR:${LIBRARY_PATH:-}"
            echo "PATH=$CLANG_DIR/bin:${PATH}"
            echo "CC=$CLANG_DIR/bin/clang"
            echo "CXX=$CLANG_DIR/bin/clang++"
            echo "CXXFLAGS=-fno-rtti -fno-exceptions -std=c++17 -DLLVM_VERSION_MAJOR=12"
            echo "RUSTFLAGS=-C linker=$CLANG_DIR/bin/clang -C link-arg=-fuse-ld=lld"
            echo "CARGO_TARGET_DIR=${{ env.AMICE_DIR }}/target-llvm12"
            echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=$CLANG_DIR/bin/clang"
          } >> "$GITHUB_ENV"

          if [ -x "$CLANG_DIR/bin/llvm-config" ]; then
            echo "LLVM_CONFIG_PATH=$CLANG_DIR/bin/llvm-config" >> "$GITHUB_ENV"
          fi

      - name: Reset ffi.cc to upstream
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          git checkout -- amice-llvm/cpp/ffi.cc
          echo "[OK] restored amice-llvm/cpp/ffi.cc"

      - name: Patch ffi.cc (guard Attribute::NoProfile for LLVM<14)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          f="amice-llvm/cpp/ffi.cc"
          if grep -q 'ENUM_CASE(llvm::Attribute::NoProfile, NoProfile)' "$f"; then
            awk '
              /ENUM_CASE\(llvm::Attribute::NoProfile, NoProfile\)/ {
                print "#if defined(LLVM_VERSION_MAJOR) && (LLVM_VERSION_MAJOR >= 14)";
                print $0;
                print "#endif";
                next
              }
              { print }
            ' "$f" > "$f.tmp"
            mv "$f.tmp" "$f"
          fi

      - name: Patch ffi.cc for LLVM 12 compatibility
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          f="amice-llvm/cpp/ffi.cc"

          # 1) Add compatibility helper code to the end of the file
          echo '' >> "$f"
          echo '// ===== AMICE compatibility helpers (portable across LLVM 12+)' >> "$f"
          echo '#if !defined(AMICE_COMPAT_HELPERS)' >> "$f"
          echo '#define AMICE_COMPAT_HELPERS 1' >> "$f"
          echo '#include <functional>' >> "$f"
          echo '#include <string>' >> "$f"
          echo 'namespace llvm { class Function; class FunctionPass; class raw_ostream; class Pass; }' >> "$f"
          echo '' >> "$f"
          echo '#if defined(LLVM_VERSION_MAJOR) && (LLVM_VERSION_MAJOR < 13)' >> "$f"
          echo '' >> "$f"
          echo '// === STUB FOR NEWER createCFGSimplificationPass SIGNATURE ===' >> "$f"
          echo '#include "llvm/Pass.h"' >> "$f"
          echo 'namespace llvm { struct SimplifyCFGOptions; }' >> "$f"
          echo 'namespace {' >> "$f"
          echo '  struct AmiceNoOpPass : public ::llvm::FunctionPass {' >> "$f"
          echo '    static char ID;' >> "$f"
          echo '    AmiceNoOpPass() : ::llvm::FunctionPass(ID) {}' >> "$f"
          echo '    bool runOnFunction(::llvm::Function&) override { return false; }' >> "$f"
          echo '  };' >> "$f"
          echo '  char AmiceNoOpPass::ID = 0;' >> "$f"
          echo '}' >> "$f"
          echo 'extern "C" ::llvm::FunctionPass* amice_cfgsimplify_stub_new(' >> "$f"
          echo '  ::llvm::SimplifyCFGOptions,' >> "$f"
          echo '  std::function<bool(::llvm::Function const&)>)' >> "$f"
          echo '  asm("_ZN4llvm27createCFGSimplificationPassENS_18SimplifyCFGOptionsESt8functionIFbRKNS_8FunctionEEE");' >> "$f"
          echo '::llvm::FunctionPass* amice_cfgsimplify_stub_new(' >> "$f"
          echo '  ::llvm::SimplifyCFGOptions,' >> "$f"
          echo '  std::function<bool(::llvm::Function const&)>)' >> "$f"
          echo '{ return new AmiceNoOpPass(); }' >> "$f"
          echo '' >> "$f"
          echo '// === STUB FOR CONST createPrinterPass SIGNATURE ===' >> "$f"
          echo 'extern "C" ::llvm::Pass* amice_printer_pass_stub(' >> "$f"
          echo '  const ::llvm::FunctionPass* self,' >> "$f"
          echo '  ::llvm::raw_ostream& OS,' >> "$f"
          echo '  const std::string& Banner)' >> "$f"
          echo '  asm("_ZNK4llvm12FunctionPass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE");' >> "$f"
          echo '::llvm::Pass* amice_printer_pass_stub(' >> "$f"
          echo '  const ::llvm::FunctionPass* self,' >> "$f"
          echo '  ::llvm::raw_ostream& OS,' >> "$f"
          echo '  const std::string& Banner)' >> "$f"
          echo '{ return const_cast<::llvm::FunctionPass*>(self)->createPrinterPass(OS, Banner); }' >> "$f"
          echo '' >> "$f"
          echo '// === STUB FOR NEWER createPrintModulePass SIGNATURE ===' >> "$f"
          echo 'extern "C" ::llvm::Pass* amice_printmodule_stub(' >> "$f"
          echo '  ::llvm::raw_ostream& OS,' >> "$f"
          echo '  const std::string& Banner,' >> "$f"
          echo '  bool ShouldPreserveUseListOrder)' >> "$f"
          echo '  asm("_ZN4llvm21createPrintModulePassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb");' >> "$f"
          echo '::llvm::Pass* amice_printmodule_stub(' >> "$f"
          echo '  ::llvm::raw_ostream& OS,' >> "$f"
          echo '  const std::string& Banner,' >> "$f"
          echo '  bool /*ShouldPreserveUseListOrder*/)' >> "$f"
          echo '{ return ::llvm::createPrintModulePass(OS, Banner); }' >> "$f"
          echo '' >> "$f"
          echo '// === STUB FOR createPrintFunctionPass SIGNATURE ===' >> "$f"
          echo 'extern "C" ::llvm::Pass* amice_print_function_pass_stub(' >> "$f"
          echo '  ::llvm::raw_ostream& OS,' >> "$f"
          echo '  const std::string& Banner)' >> "$f"
          echo '  asm("_ZN4llvm23createPrintFunctionPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE");' >> "$f"
          echo '::llvm::Pass* amice_print_function_pass_stub(' >> "$f"
          echo '  ::llvm::raw_ostream& OS,' >> "$f"
          echo '  const std::string& Banner)' >> "$f"
          echo '{ return ::llvm::createPrintFunctionPass(OS, Banner); }' >> "$f"
          echo '' >> "$f"
          echo '// Forward decls for functions that actually exist in LLVM 12' >> "$f"
          echo 'namespace llvm {' >> "$f"
          echo '  FunctionPass* createCFGSimplificationPass(' >> "$f"
          echo '      unsigned, bool, bool, bool, bool, std::function<bool(const ::llvm::Function&)>);' >> "$f"
          echo '  Pass* createPrintModulePass(raw_ostream& OS, const std::string& Banner = "");' >> "$f"
          echo '  FunctionPass* createPrintFunctionPass(raw_ostream& OS, const std::string& Banner);' >> "$f"
          echo '}' >> "$f"
          echo '#endif' >> "$f"
          echo '' >> "$f"
          echo '// This is the main helper that our sed command will redirect calls to.' >> "$f"
          echo 'static ::llvm::FunctionPass* AMICE_makeCFGSimplify() {' >> "$f"
          echo '#if defined(LLVM_VERSION_MAJOR) && (LLVM_VERSION_MAJOR >= 13)' >> "$f"
          echo '  #include "llvm/Transforms/Utils/SimplifyCFGOptions.h"' >> "$f"
          echo '  ::llvm::SimplifyCFGOptions Opts{};' >> "$f"
          echo '  return ::llvm::createCFGSimplificationPass(Opts, nullptr);' >> "$f"
          echo '#else' >> "$f"
          echo '  return ::llvm::createCFGSimplificationPass(1, false, false, true, false, nullptr);' >> "$f"
          echo '#endif' >> "$f"
          echo '}' >> "$f"
          echo '' >> "$f"
          echo '// Stub for missing LLVMIsTypeAttribute in LLVM < 13' >> "$f"
          echo '#if defined(LLVM_VERSION_MAJOR) && (LLVM_VERSION_MAJOR < 13)' >> "$f"
          echo 'extern "C" {' >> "$f"
          echo '  typedef struct LLVMOpaqueAttributeRef *LLVMAttributeRef;' >> "$f"
          echo '  typedef int LLVMBool;' >> "$f"
          echo '  LLVMBool LLVMIsTypeAttribute(LLVMAttributeRef) { return 0; }' >> "$f"
          echo '}' >> "$f"
          echo '#endif' >> "$f"
          echo '' >> "$f"
          echo '#endif // AMICE_COMPAT_HELPERS' >> "$f"
          echo '// ===== end helpers' >> "$f"

          # 2) Replace all calls to createCFGSimplificationPass(...) with the helper
          sed -E -i 's/::llvm::createCFGSimplificationPass\([^;]*\)/AMICE_makeCFGSimplify()/g' "$f"
          sed -E -i 's/([^:])createCFGSimplificationPass\([^;]*\)/\1AMICE_makeCFGSimplify()/g' "$f"

          # 3) Patch CodeExtractor constructor call for LLVM 12 by removing extra arguments
          sed -i 's/::llvm::CodeExtractor(Blocks, &DT, false, &BFI, &BPI, &AC, true, false, ".split")/::llvm::CodeExtractor(Blocks, \&DT, false, \&BFI, \&BPI, \&AC, true)/g' "$f"


          echo "== Preview tail of ffi.cc =="
          tail -n 120 "$f" || true

      - name: Build libamice.so (feature llvm12-0)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          cargo clean
          cargo build --release --no-default-features --features llvm12-0
          mkdir -p "$OUT_DIR"
          cp -v target-llvm12/release/libamice.so "$OUT_DIR/"

      - name: Smoke test:load plugin with this clang
        shell: bash
        run: |
          set -euo pipefail
          echo 'int main(){return 0;}' > /tmp/t.c
          "$CLANG_DIR/bin/clang" -fpass-plugin="$OUT_DIR/libamice.so" -O2 -xc /tmp/t.c -o /tmp/t

      - name: Upload artifact (libamice.so for clang-r416183c1)
        uses: actions/upload-artifact@v4
        with:
          name: libamice-ndk-r23b-clang-r416183c1
          path: ${{ env.OUT_DIR }}/libamice.so
          if-no-files-found: error

