name: linux-x64-build-android-ndk-r23b (libamice.so via clang-r416183c1)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      AMICE_DIR: ${{ github.workspace }}/amice
      OUT_DIR: ${{ github.workspace }}/out
      CLANG_DIR: ${{ github.workspace }}/clang-r416183c1
      # Unstripped clang r416183c1 (LLVM 12)
      CLANG_UNSTRIPPED_URL: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/c3260b409f13d92f8c9f4795420238694c529352/clang-r416183c1.tar.gz

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4

      - name: Checkout amice source
        uses: actions/checkout@v4
        with:
          repository: fuqiuluo/amice
          ref: master
          path: amice

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo (amice)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ env.AMICE_DIR }}/target-llvm12
          key: ${{ runner.os }}-cargo-amice-${{ hashFiles('amice/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-amice-

      - name: Prepare folders
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$OUT_DIR" "$CLANG_DIR"

      - name: Download unstripped Clang r416183c1 (LLVM 12)
        shell: bash
        run: |
          set -euo pipefail
          curl -fL "$CLANG_UNSTRIPPED_URL" -o /tmp/clang-r416183c1.tar.gz
          tar -xzf /tmp/clang-r416183c1.tar.gz -C "$CLANG_DIR"
          "$CLANG_DIR/bin/clang++" --version || true
          ls -l "$CLANG_DIR/lib"  || true
          ls -l "$CLANG_DIR/lib64"|| true

      - name: Normalize LLVM dylib name (handle libLLVM-12git.so)
        shell: bash
        run: |
          set -euo pipefail
          FOUND="$(find "$CLANG_DIR" -maxdepth 3 -type f -name 'libLLVM-12*.so' | head -n1 || true)"
          if [ -z "$FOUND" ]; then
            echo "libLLVM-12*.so not found under $CLANG_DIR"
            find "$CLANG_DIR" -maxdepth 3 -name 'libLLVM*.so' -ls || true
            exit 1
          fi
          LIBDIR="$(dirname "$FOUND")"
          BASENAME="$(basename "$FOUND")"
          ln -sf "$BASENAME" "$LIBDIR/libLLVM-12.so"
          ln -sf "$BASENAME" "$LIBDIR/libLLVM.so"
          ls -l "$LIBDIR"/libLLVM*.so

          {
            echo "LLVM_SYS_120_PREFIX=$CLANG_DIR"
            echo "LD_LIBRARY_PATH=$LIBDIR"
            echo "LIBRARY_PATH=$LIBDIR"
            echo "PATH=$CLANG_DIR/bin:${PATH}"
            echo "CC=$CLANG_DIR/bin/clang"
            echo "CXX=$CLANG_DIR/bin/clang++"
            # Match libLLVM prebuilts (disable RTTI/exception) + define version
            echo "CXXFLAGS=-fno-rtti -fno-exceptions -std=c++17 -DLLVM_VERSION_MAJOR=12"
          } >> "$GITHUB_ENV"

          if [ -x "$CLANG_DIR/bin/llvm-config" ]; then
            echo "LLVM_CONFIG_PATH=$CLANG_DIR/bin/llvm-config" >> "$GITHUB_ENV"
          fi

      - name: Use clang + ld.lld as Rust linker
        shell: bash
        run: |
          set -euo pipefail
          {
            echo "RUSTFLAGS=-C linker=$CLANG_DIR/bin/clang -C link-arg=-fuse-ld=lld"
            echo "CARGO_TARGET_DIR=${{ env.AMICE_DIR }}/target-llvm12"
            echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=$CLANG_DIR/bin/clang"
          } >> "$GITHUB_ENV"

      - name: Patch for LLVM 12 (guard NoProfile enum)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          f="amice-llvm/cpp/ffi.cc"
          if [ -f "$f" ]; then
            tmp="${f}.tmp"
            awk '
              /ENUM_CASE\(llvm::Attribute::NoProfile, NoProfile\)/ {
                print "#if defined(LLVM_VERSION_MAJOR) && LLVM_VERSION_MAJOR >= 14";
                print $0;
                print "#endif";
                next
              }
              { print }
            ' "$f" > "$tmp"
            mv "$tmp" "$f"
            grep -n "NoProfile" "$f" || true
          fi

      # NEW: Patch the function call that causes the undefined symbol error
      - name: Patch for LLVM 12 (fix createCFGSimplificationPass call)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          f="amice-llvm/cpp/transforms.cc"
          if [ -f "$f" ]; then
            # LLVM 12's createCFGSimplificationPass doesn't take the std::function argument.
            # This patch removes the arguments to match the older API.
            sed -i 's/createCFGSimplificationPass(Options.SimplifyCFG, is_fn_hot)/createCFGSimplificationPass()/' "$f"
            echo "Patched createCFGSimplificationPass in $f"
            grep "createCFGSimplificationPass" "$f" || true
          else
            echo "Warning: $f not found, skipping patch."
          fi

      # Safe stub for LLVM<13
      - name: Patch for LLVM 12 (stub LLVMIsTypeAttribute for LLVM<13)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          f="amice-llvm/cpp/ffi.cc"
          echo '' >> "$f"
          echo '#if defined(LLVM_VERSION_MAJOR) && LLVM_VERSION_MAJOR < 13' >> "$f"
          echo 'extern "C" {' >> "$f"
          echo '  /* Forward typedefs (no llvm-c headers needed) */' >> "$f"
          echo '  typedef struct LLVMOpaqueAttributeRef *LLVMAttributeRef;' >> "$f"
          echo '  typedef int LLVMBool;' >> "$f"
          echo '  LLVMBool LLVMIsTypeAttribute(LLVMAttributeRef /*A*/) {' >> "$f"
          echo '    /* LLVM 12 is missing this symbol in C API; return 0 to avoid unresolved symbols. */' >> "$f"
          echo '    return 0;' >> "$f"
          echo '  }' >> "$f"
          echo '}' >> "$f"
          echo '#endif' >> "$f"

      - name: Build libamice.so (feature llvm12-0)
        shell: bash
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -euo pipefail
          cargo clean
          cargo build --release --no-default-features --features llvm12-0
          mkdir -p "$OUT_DIR"
          cp -v target-llvm12/release/libamice.so "$OUT_DIR/"

      - name: Smoke test:show deps and compile a tiny TU
        shell: bash
        run: |
          set -euo pipefail
          ldd "$OUT_DIR/libamice.so" || true
          echo 'int main(){return 0;}' > /tmp/t.c
          "$CLANG_DIR/bin/clang" -O2 -xc /tmp/t.c -o /tmp/t

      - name: Upload artifact (libamice.so for clang-r416183c1)
        uses: actions/upload-artifact@v4
        with:
          name: libamice-ndk-r23b-clang-r416183c1
          path: ${{ env.OUT_DIR }}/libamice.so
          if-no-files-found: error

