name: linux-x64-build-android-ndk-r23 (libamice.so via clang-r416183b1)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      # Thư mục làm việc
      AMICE_DIR: ${{ github.workspace }}/amice
      OUT_DIR: ${{ github.workspace }}/out

      # Unstripped Clang (LLVM 12) bạn chỉ định: r416183b1
      CLANG_DIR: ${{ github.workspace }}/clang-r416183b1
      CLANG_UNSTRIPPED_URL: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/219e6aaa8fecc0ab0df4e691a9645ba778267af2/clang-r416183b1.tar.gz

    steps:
      - name: Checkout (this repo)
        uses: actions/checkout@v4

      - name: Checkout amice source
        uses: actions/checkout@v4
        with:
          repository: fuqiuluo/amice
          ref: master
          path: amice

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo (amice)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ${{ env.AMICE_DIR }}/target
          key: ${{ runner.os }}-cargo-amice-${{ hashFiles('amice/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-amice-

      - name: Prepare folders
        run: |
          set -eux
          mkdir -p "$OUT_DIR" "$CLANG_DIR"

      - name: Download unstripped Clang r416183b1 (LLVM 12)
        run: |
          set -eux
          curl -fL "$CLANG_UNSTRIPPED_URL" -o /tmp/clang-r416183b1.tar.gz
          tar -xzf /tmp/clang-r416183b1.tar.gz -C "$CLANG_DIR"
          "$CLANG_DIR/bin/clang++" --version || true
          ls -l "$CLANG_DIR/lib"  || true
          ls -l "$CLANG_DIR/lib64"|| true

      - name: Configure env for llvm-sys 12 (NDK r23 family)
        run: |
          set -eux
          echo "LLVM_SYS_120_PREFIX=$CLANG_DIR" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$CLANG_DIR/lib:$CLANG_DIR/lib64:${LD_LIBRARY_PATH:-}" >> $GITHUB_ENV

      - name: Build libamice.so (feature LLVM 12.0)
        working-directory: ${{ env.AMICE_DIR }}
        run: |
          set -eux
          cargo build --release --no-default-features --features llvm12-0
          cp -v target/release/libamice.so "$OUT_DIR/"

      - name: Smoke test:load plugin with this clang
        run: |
          set -eux
          echo 'int main(){return 0;}' > /tmp/t.c
          "$CLANG_DIR/bin/clang" -fpass-plugin="$OUT_DIR/libamice.so" -O2 -xc /tmp/t.c -o /tmp/t

      - name: Upload artifact (libamice.so for clang-r416183b1)
        uses: actions/upload-artifact@v4
        with:
          name: libamice-ndk-r23-clang-r416183b1
          path: ${{ env.OUT_DIR }}/libamice.so
          if-no-files-found: error
